language: php

cache:
  directories:
    - bin
    - vendor

php:
  - 7.4
  - 8.0

before_script:
  - composer selfupdate
  - composer install --dev --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - travis_retry php bin/coveralls -v
